name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Tox on Fedora
        uses: fedora-python/tox-github-action@v0.3
        with:
          tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py27, py35, py36, py37, py38, py39, pypy2, pypy3]
